name: Provision
description: Set up job with tasks needed to run a code check
runs:
  using: 'composite'
  steps:
    - name: Install yarn dependencies
      run: yarn --frozen-lockfile
      shell: bash
