[[redirects]]
  from = "/actions.html"
  to = "/#/sign-up?authRequest=:authRequest"
  force = true
  query = {authRequest = ":authRequest"}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self'; img-src https://*; style-src 'unsafe-inline'; object-src 'none'; frame-src 'none'; connect-src 'self' stats.blockstack.xyz hub.blockstack.org core.blockstack.org registrar.blockstack.org gaia.blockstack.org;"
