name: 'Integration Tests'
description: 'Run integration tests'
runs:
  using: 'composite'
  steps:
    - name: Clear node_modules
      shell: bash
      run: rm -rf node_modules
    - name: Install dependencies
      shell: bash
      run: yarn --frozen-lockfile
    - name: Build web apps
      shell: bash
      run: yarn build:test
    - name: Integration Tests
      shell: bash
      run: |
        yarn serve:test &
        cd packages/app &&
        yarn test:integration
