name: Publish Extensions
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  publish_chrome_extension:
    name: Publish Chrome extension
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Version Packages')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.21.0
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Build extension
        run: sh build-ext.sh

      - name: Sign and Upload Production Chrome extension
        continue-on-error: true
        run: yarn webstore upload --source stacks-wallet-chromium.zip --auto-publish
        env:
          EXTENSION_ID: ${{ secrets.CHROME_APP_ID }}
          CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}

  publish_firefox_extension:
    name: Publish Firefox extension
    runs-on: ubuntu-latest
    env:
      MINIFY_PRODUCTION_BUILD: true
    if: "contains(github.event.head_commit.message, 'Version Packages')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.21.0
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Build extension
        run: sh build-ext.sh

      - name: Sign and Upload Production Firefox extension
        continue-on-error: true
        run: yarn web-ext-submit --channel=listed
        env:
          WEB_EXT_API_KEY: ${{ secrets.FIREFOX_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.FIREFOX_API_SECRET }}
