name: Pull Request
on: [pull_request, workflow_dispatch]

jobs:
  check_fork:
    name: Disable jobs for forks
    runs-on: ubuntu-latest
    outputs:
      is_not_fork: ${{ steps.is_not_fork.outputs.is_not_fork }}
    steps:
      - name: Check for secret
        id: is_not_fork
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          STABLE_WALLET_BRANCH: ${{ secrets.STABLE_WALLET_BRANCH }}
        run: |
          echo "Is a fork: ${{ env.WEB_EXT_API_KEY == '' }}"
          echo "::set-output name=is_not_fork::${{ env.WEB_EXT_API_KEY != '' }}"
          echo "::set-output name=stable_wallet_branch::${{ env.STABLE_WALLET_BRANCH }}"

  commitlint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1

  code_checks:
    needs: [check_fork]
    name: Code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: lucasmotta/pull-request-sticky-header@1.0.0
        if: needs.check_fork.outputs.is_not_fork == 'true'
        with:
          header: '> Try out this version of the Stacks Wallet - download [extension builds](https://github.com/blockstack/ux/actions/runs/${{ github.run_id }}).'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Node Version
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.21.0
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Code Checks
        uses: ./.github/actions/code-checks
      - name: Check exact versions
        uses: ./.github/actions/check-version-lock
      - uses: actions/upload-artifact@v2
        name: Upload Chrome Extension Zip
        with:
          name: stacks-wallet-chromium
          path: stacks-wallet-chromium.zip

  integration_tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.21.0
      - uses: microsoft/playwright-github-action@v1
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Integration Tests
        uses: ./.github/actions/integration-tests
      - uses: actions/upload-artifact@v2
        if: always()
        name: Upload Screenshots
        with:
          name: integration-test-screenshots
          path: tests/screenshots/

  publish_firefox_beta:
    name: Publish beta firefox extension
    runs-on: ubuntu-latest
    needs: [check_fork]
    if: needs.check_fork.outputs.is_not_fork == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set Node Version
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.21.0
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Build extension
        run: sh build-ext.sh
      - name: Sign Firefox extension
        run: yarn web-ext sign --channel=unlisted
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      - uses: actions/upload-artifact@v2
        name: Upload Firefox Add-On XPI
        with:
          name: connect-addon
          path: web-ext-artifacts/*.xpi
