name: Version
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  COMMIT_USER: Hiro DevOps
  COMMIT_EMAIL: 45208873+blockstack-devops@users.noreply.github.com

jobs:
  pre-run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@ad6cb1b847ffb509a69b745b6ee2f1d14dfe14b8
        with:
          access_token: ${{ github.token }}

  upload-extension:
    name: Upload extension
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Version Packages')"
    needs:
      - pre-run
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node Version
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.21.0

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Check exact versions
        uses: ./.github/actions/check-version-lock

      - uses: actions/upload-artifact@v2
        name: Upload Chrome Extension Zip
        with:
          name: stacks-wallet-chromium
          path: stacks-wallet-chromium.zip

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Version Packages')"
    needs:
      - pre-run
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node Version
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.21.0

      - uses: microsoft/playwright-github-action@v1

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Integration Tests
        uses: ./.github/actions/integration-tests

      - uses: actions/upload-artifact@v2
        if: always()
        name: Upload Screenshots
        with:
          name: integration-test-screenshots
          path: tests/screenshots/

  version:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Version Packages')"
    needs:
      - integration-tests
      - upload-extension
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Set Node Version
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.21.0

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Create Release Pull Request
        uses: changesets/action@640c4a5d646991720131ef3b6e0e63220de5dddf
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
