name: 'Code Checks'
description: 'Run tests, linting, and other common jobs'
runs:
  using: 'composite'
  steps:
    - name: Install yarn dependencies
      run: yarn --frozen-lockfile
      shell: bash
    - name: Lint
      run: yarn lint
      shell: bash
    - name: Typecheck
      run: yarn typecheck
      shell: bash
    - name: Audit dependencies
      shell: bash
      run: yarn audit
    - name: App unit tests
      run: yarn test:unit
      shell: bash
    - name: Build project
      run: yarn build
      shell: bash
    - name: Build extension
      run: sh build-ext.sh
      shell: bash
    - name: Setup screenshots
      shell: bash
      run: mkdir tests/screenshots
    - name: Check dependencies
      run: yarn check:deps
      shell: bash
